### PR TITLE
Added logstash 6.x support (multi pipeline)

### PR DESCRIPTION
**Pull request by runningman84**
## Pull Request Checklist

https://github.com/sensu-plugins/sensu-plugins-logstash/issues/25

#### General

- [ ] Update Changelog following the conventions laid out [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Review by runningman84 — COMMENTED** [review]
fix v5 support

**Comment by majormoses** [comment]
@runningman84 can you fixup tests?

**Comment by runningman84** [comment]
I do not really see what is wrong here.

**Comment by majormoses** [comment]
I will see if I can spend some time this weekend looking at the tests and see if the tests need to be modified or if the changes are actually breaking the testing use cases.

**Comment by majormoses** [comment]
sorry for the long delay I finally had some time to dig into this and while I did not exactly figure out what caused the error it seemed like it should only check if you have `pipeline` or `pipelines` not both unless that is supported?
I got the tests to pass with the following changes from master:
```
$ git diff
diff --git a/bin/metrics-logstash-node.rb b/bin/metrics-logstash-node.rb
index d8251b3..83c16be 100755
--- a/bin/metrics-logstash-node.rb
+++ b/bin/metrics-logstash-node.rb
@@ -113,31 +113,62 @@ class LogstashNodeMetrics < Sensu::Plugin::Metric::CLI::Graphite
     metrics['process.peak_open_file_descriptors'] = node['process']['peak_open_file_descriptors']
     metrics['process.max_file_descriptors'] = node['process']['max_file_descriptors']
 
-    node['pipeline']['events'].each do |key, value|
-      metrics["pipeline.events.#{key}"] = value
-    end
-
-    node['pipeline']['plugins']['inputs'].each do |item|
-      item['events'] = {} unless item.key?('events')
-      metrics["pipeline.plugins.inputs.#{item['name']}.#{item['id']}.events.in"] = item['events']['in'].to_i || 0
-      metrics["pipeline.plugins.inputs.#{item['name']}.#{item['id']}.events.out"] = item['events']['out'].to_i || 0
-      metrics["pipeline.plugins.inputs.#{item['name']}.#{item['id']}.events.queue_push_duration_in_millis"] = \
-        item['events']['queue_push_duration_in_millis'].to_i || 0
-    end
-
-    node['pipeline']['plugins']['filters'].each do |item|
-      item['events'] = {} unless item.key?('events')
-      metrics["pipeline.plugins.filters.#{item['name']}.#{item['id']}.events.in"] = item['events']['in'].to_i || 0
-      metrics["pipeline.plugins.filters.#{item['name']}.#{item['id']}.events.out"] = item['events']['out'].to_i || 0
-      metrics["pipeline.plugins.filters.#{item['name']}.#{item['id']}.events.duration_in_millis"] = item['events']['duration_in_millis'].to_i || 0
-      metrics["pipeline.plugins.filters.#{item['name']}.#{item['id']}.matches"] = item['matches'].to_i if item.key?('matches')
-    end
-
-    node['pipeline']['plugins']['outputs'].each do |item|
-      item['events'] = {} unless item.key?('events')
-      metrics["pipeline.plugins.outputs.#{item['name']}.#{item['id']}.events.in"] = item['events']['in'].to_i || 0
-      metrics["pipeline.plugins.outputs.#{item['name']}.#{item['id']}.events.out"] = item['events']['out'].to_i || 0
-      metrics["pipeline.plugins.outputs.#{item['name']}.#{item['id']}.events.duration_in_millis"] = item['events']['duration_in_millis'].to_i || 0
+    # logstash < 6.0
+    if node.key?('pipeline')
+      node['pipeline']['events'].each do |key, value|
+        metrics["pipeline.events.#{key}"] = value
+      end
+
+      node['pipeline']['plugins']['inputs'].each do |item|
+        item['events'] = {} unless item.key?('events')
+        metrics["pipeline.plugins.inputs.#{item['name']}.#{item['id']}.events.in"] = item['events']['in'].to_i || 0
+        metrics["pipeline.plugins.inputs.#{item['name']}.#{item['id']}.events.out"] = item['events']['out'].to_i || 0
+        metrics["pipeline.plugins.inputs.#{item['name']}.#{item['id']}.events.queue_push_duration_in_millis"] = \
+          item['events']['queue_push_duration_in_millis'].to_i || 0
+      end
+
+      node['pipeline']['plugins']['filters'].each do |item|
+        metrics["pipeline.plugins.filters.#{item['name']}.#{item['id']}.events.out"] = item['events']['out'].to_i || 0
+        metrics["pipeline.plugins.filters.#{item['name']}.#{item['id']}.events.duration_in_millis"] = item['events']['duration_in_millis'].to_i || 0
+        metrics["pipeline.plugins.filters.#{item['name']}.#{item['id']}.matches"] = item['matches'].to_i if item.key?('matches')
+      end
+
+      node['pipeline']['plugins']['outputs'].each do |item|
+        item['events'] = {} unless item.key?('events')
+        metrics["pipeline.plugins.outputs.#{item['name']}.#{item['id']}.events.in"] = item['events']['in'].to_i || 0
+        metrics["pipeline.plugins.outputs.#{item['name']}.#{item['id']}.events.out"] = item['events']['out'].to_i || 0
+        metrics["pipeline.plugins.outputs.#{item['name']}.#{item['id']}.events.duration_in_millis"] = item['events']['duration_in_millis'].to_i || 0
+      end
+    # logstash >= 6.0
+    elsif node.key?('pipelines')
+      node['pipelines'].each_key do |pipeline|
+        node['pipelines'][pipeline]['events'].each do |key, value|
+          metrics["pipelines.#{pipeline}.events.#{key}"] = value
+        end
+
+        node['pipelines'][pipeline]['plugins']['inputs'].each do |item|
+          item['events'] = {} unless item.key?('events')
+          metrics["pipelines.#{pipeline}.plugins.inputs.#{item['name']}.#{item['id']}.events.in"] = item['events']['in'].to_i || 0
+          metrics["pipelines.#{pipeline}.plugins.inputs.#{item['name']}.#{item['id']}.events.out"] = item['events']['out'].to_i || 0
+          metrics["pipelines.#{pipeline}.plugins.inputs.#{item['name']}.#{item['id']}.events.queue_push_duration_in_millis"] = item['events']['queue_push_duration_in_millis'].to_i || 0 # rubocop:disable Metrics/LineLength
+        end
+
+        node['pipelines'][pipeline]['plugins']['filters'].each do |item|
+          item['events'] = {} unless item.key?('events')
+          metrics["pipelines.#{pipeline}.plugins.filters.#{item['name']}.#{item['id']}.events.in"] = item['events']['in'].to_i || 0
+          metrics["pipelines.#{pipeline}.plugins.filters.#{item['name']}.#{item['id']}.events.out"] = item['events']['out'].to_i || 0
+          metrics["pipelines.#{pipeline}.plugins.filters.#{item['name']}.#{item['id']}.events.duration_in_millis"] = item['events']['duration_in_millis'].to_i || 0 # rubocop:disable Metrics/LineLength
+          metrics["pipelines.#{pipeline}.plugins.filters.#{item['name']}.#{item['id']}.matches"] = item['matches'].to_i if item.key?('matches')
+        end
+
+        node['pipelines'][pipeline]['plugins']['outputs'].each do |item|
+          item['events'] = {} unless item.key?('events')
+          metrics["pipelines.#{pipeline}.plugins.outputs.#{item['name']}.#{item['id']}.events.in"] = item['events']['in'].to_i || 0
+          metrics["pipelines.#{pipeline}.plugins.outputs.#{item['name']}.#{item['id']}.events.out"] = item['events']['out'].to_i || 0
+        end
+      end
     end
 
     metrics.each do |k, v|
```

You can either try manually applying the changes to your existing commits or create a new commit with the current HEAD and add it as a new commit.

Using the patch method checking out the old commit (though you probably want to reset rather than checkout):
```
$ git checkout 4ca3f7b4bc44a0d74a9b766659cf5cde57149a0d
Note: checking out '4ca3f7b4bc44a0d74a9b766659cf5cde57149a0d'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at 4ca3f7b... prep for 2.0.0 release

```
Apply the patch:
```
$ git apply logstash6_compat.patch
$ git status 
HEAD detached at 4ca3f7b
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   bin/metrics-logstash-node.rb

Untracked files:
  (use "git add <file>..." to include in what will be committed)

	logstash6_compat.patch

no changes added to commit (use "git add" and/or "git commit -a")
```

Run the tests:
```
$ bundle exec rake default
/home/babrams/.rbenv/versions/2.3.5/bin/ruby -I/home/babrams/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/lib:/home/babrams/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-support-3.7.1/lib /home/babrams/.rbenv/versions/2.3.5/lib/ruby/gems/2.3.0/gems/rspec-core-3.7.1/exe/rspec test/metrics-logstash_spec.rb
...

Finished in 0.00958 seconds (files took 0.32827 seconds to load)
3 examples, 0 failures

Files:           3
Modules:         2 (    2 undocumented)
Classes:         2 (    0 undocumented)
Constants:       4 (    4 undocumented)
Attributes:      0 (    0 undocumented)
Methods:         6 (    5 undocumented)
 21.43% documented
Running RuboCop...
/home/babrams/.rubocop.yml: Naming/AccessorMethodName has the wrong namespace - should be Style
/home/babrams/.rubocop.yml: Layout/SpaceBeforeFirstArg has the wrong namespace - should be Style
Inspecting 9 files
.........

9 files inspected, no offenses detected


```

**Comment by majormoses** [comment]
I tried to attach the patch file but ironically github comments don't support adding a patch file I will create it as a gist and share it here

**Comment by majormoses** [comment]
see the patch file here: https://gist.github.com/majormoses/9f604bbb995c5c566b5bf643b1eff5e2

**Review by majormoses — CHANGES_REQUESTED** [review]
Your change breaks the tests, I have given you a patch that you can apply to fix it without breaking anything.

**Comment by Evesy** [comment]
>  it seemed like it should only check if you have pipeline or pipelines not both unless that is supported?

@majormoses This is correct from some testing I've done -- The stats API appears to always return `pipelines` now as a top level key, even if you do only have one pipeline

@runningman84 Are you likely going to be able to apply the patch provided sometime soon, I'd certainly appreciate the new release 👍Happy to help if there's anything I can do

**Comment by runningman84** [comment]
I am out of office this week I can take a look next week. Feel free to patch yourself and create a new pull request meanwhile.

**Comment by majormoses** [comment]
closing in favor of #28 I have ensured you got credit as a co-author as you did the bulk of the work

**Pull request closed without merging**
