### PR TITLE
Support multiple outputs in Logstash handler

### PR DESCRIPTION
**Pull request by Evesy**
## Pull Request Checklist

**Is this in reference to an existing issue?**
No

#### General

- [x] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [x] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [x] RuboCop passes

- [x] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

#### Purpose
There is a need to send Logstash events to more than one endpoint, this change will allow you to specify several different endpoints (Address, host, output type), all of which will be looped through and the event sent.

This is an alternative, hopefully more lightweight, method to having multiple logstash handlers running for every event, which could become quite resource intensive.

#### Known Compatablity Issues
Breaking change.
Logstash handler settings will require updating along with the gem, else the handler will fail.

### CODE REVIEW

**Comment by Evesy** [comment]
@majormoses Reopened the PR here as the original repo was no more. Build tests have failed though, not entirely sure why

**Comment by majormoses** [comment]
@Evesy looks like its failing ruby 1.9 which I am ok with dropping support for. Do you need help with removing this? If so you can give me access to the branch on your PR and I can work on that for you.

**Comment by Evesy** [comment]
@majormoses Please go ahead, I've added you as a collaborator

**Comment by Evesy** [comment]
@majormoses Should we also test for 2.4 since latest Sensu release ships with this version?

**Comment by majormoses** [comment]
@Evesy dropped ruby 1.9 and added ruby 2.3 (will add ruby 2.4 shortly but wanted to limit the scope as 2.4 has some breaking changes and could cause this to fail. As I am a maintainer I can do that quickly outside of the scope of this PR.

**Comment by majormoses** [comment]
@Evesy after reading the PR more (initially I just looked at travis) I would move your change to Breaking Changes section reviewing the code as this will break for all existing users no?

**Comment by Evesy** [comment]
@majormoses Yep, this is 100% a breaking change for existing users. I'm not familiar with this breaking changes section though?

**Comment by majormoses** [comment]
I am not 100% sure that others do this but I think its super helpful to always call out breaking changes to be called out from other changes as this allows users to quickly evaluate upgrades. I will update the PR with this.

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-logstash/versions/1.0.0

**Comment by majormoses** [comment]
@Evesy added ruby 2.4 testing here: https://github.com/sensu-plugins/sensu-plugins-logstash/pull/20

**Pull request merged**
