### PR TITLE
Added logstash metrics

### PR DESCRIPTION
**Pull request by runningman84**
## Pull Request Checklist

**Is this in reference to an existing issue?**

#### General

- [ ] Update Changelog following the conventions laid out on [Keep A Changelog](http://keepachangelog.com/)

- [ ] Update README with any necessary configuration snippets

- [ ] Binstubs are created if needed

- [ ] RuboCop passes

- [ ] Existing tests pass 

#### New Plugins

- [ ] Tests

- [ ] Add the plugin to the README

- [ ] Does it have a complete header as outlined [here](http://sensu-plugins.io/docs/developer_guidelines.html#coding-style)

### CODE REVIEW

**Comment by majormoses** [comment]
@runningman84 any chance of fixing this up?

**Comment by runningman84** [comment]
I have no idea what is wrong here becase I do not see the build log anymore... it works for me.

**Comment by majormoses** [comment]
I restarted it: https://travis-ci.org/sensu-plugins/sensu-plugins-logstash/builds/183639756 I will check back in a bit and see if it fails

**Comment by majormoses** [comment]
yup, still have issues can you clean those up?

**Comment by runningman84** [comment]
I fixed all obvious errors. I assume that this error means the run function is too long:
`metrics-logstash-node:96:3: C: Assignment Branch Condition size for run is too high. [101.3/100]`
Please increase the limit or feel free to split everything up into smaller parts...

**Comment by majormoses** [comment]
@runningman84 that means there are too many conditions (if, unless, etc). I would need to look more but I often solve this by breaking out logic into (class) helper functions.

**Comment by majormoses** [comment]
@runningman84 if you want you can just disable it for now inline and at some point we can come back and asses it's performance and determine if we should re-write it to be more efficient.

**Comment by runningman84** [comment]
That sounds great. How can you disable the check inline?

**Comment by majormoses** [comment]
pretty sure that's covered here: `# rubocop:disable Metrics/AbcSize`

**Comment by majormoses** [comment]
I think you misunderstood what I meant, just append it to the offending line like this:
```
def run # rubocop:disable Metrics/AbcSize
```

Which only disables it for that line.

**Comment by majormoses** [comment]
@runningman84 ok Ill pull it locally and figure out how to appease the rubocop.

**Comment by majormoses** [comment]
just whitespace now:
```
metrics-logstash-node:95:1: C: Trailing whitespace detected.
metrics-logstash-node:145:1: C: Trailing whitespace detected.
```

**Review by majormoses — CHANGES_REQUESTED** [review]
lets name the file with a `.rb` and move it to the `bin/` folder. Developer guidelines talking about some of this: https://github.com/sensu-plugins/documentation/blob/master/docs/developer_guidelines.md#naming-conventions I would also like to see a testing artifact (ideally a unit test), if not I would take a gist or screenshot of some input and output to verify it is working.

**Comment by majormoses** [comment]
also metric collectors should prefix this like this: `metrics-some-metric-output.rb`

**Comment by majormoses** [comment]
@runningman84 any plans to get back to this?

**Comment by runningman84** [comment]
Sorry I am out of office for the next weeks. I will ask a coworker to put some output of this plugin into gist. I have moved the file to the bin folder.
@autarchprinceps can you past a sample output from some of our test nodes?

**Comment by autarchprinceps** [comment]
This should be what you wanted, right?

[Logstash metrics output](https://gist.github.com/autarchprinceps/85afb950d71680a6b9c8300b803329ba)

**Review by majormoses — APPROVED** [review]
LGTM

**Comment by majormoses** [comment]
@autarchprinceps I'd normally like to see the command with the args passed as that changes the behavior but this gives me the confidence it has actually been tested which is the primary concern. You would be surprised how many times people do not test the code they submit.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-logstash/versions/1.1.0

**Pull request merged**
